### ISSUE TITLE
No package XXXX found in local repositories specified

### ISSUE THREAD

**Issue by csgillespie** [rstudio/shinyapps#194]
I'm trying to upload an app to shinyapps.io, however, I get the following error:

```
R> shinyapps::deployApp('~/github/benchmarkme-data/inst/shinyExamples/plotting/')
Preparing to deploy application...DONE
Uploading bundle for application: 83537...
Error in findLocalRepoForPkg(pkg, repos, fatal = fatal) : 
  No package 'benchmarkmeData' found in local repositories specified
```
The app depends on a package that is hosted on a github drat repo. I've tried adding

```
options(repos=c("drat"="http://csgillespie.github.io/drat/", 
                "CRAN"="https://cran.rstudio.org"))
library("benchmarkmeData")
```
to the top of server.R/ui.R, but I still get the same error. I've also tried various incantations of `install_github` and `install.packages`

**Comment by kevinushey** [comment]
This sounds like an error message coming from `packrat`; are you using `packrat` to manage your application? How is the `benchmarkmeData` package referenced?

**Comment by csgillespie** [comment]
I'm just using a standard rstudio project. The package is referenced via `library(benchmarkmeData)` - as in https://github.com/csgillespie/benchmarkme-data/tree/master/inst/shinyExamples/plotting

**Comment by aronatkins** [comment]
@kevinushey Packrat is used to analyze/snapshot the dependencies of an application. We no longer have two ways of computing dependency information in `shinyapps`/`rsconnect`.

**Comment by csgillespie** [comment]
I've deleted and reinstalled packrat, shinyapps, and rsconnect

**Comment by kevinushey** [comment]
@csgillespie I just pushed a fix for this particular issue to the development version of packrat; can you try

    devtools::install_github('rstudio/packrat')

and see if this helps? Note that although the error message is bogus, it indicates that 'benchmarkmeData' wasn't found in any of your repositories.

You might also need to set `options(pkgType = "source")` if you're using a drat repository.

**Comment by csgillespie** [comment]
Updated `packrat` - still no luck. I've also tried the `pkgType` suggestion.

The top two lines of `ui.R` and `server.R` are

```
options(repos=c("CRAN" ="https://cran.rstudio.com/", 
                "csgillespie"="http://csgillespie.github.io/drat/"),
        pkgType = "source")

library("benchmarkmeData")
```

This points to the correct repo since

```
install.package("benchmarkmeData")
```

works. The package is also installed on my machine.

----

The error I get is:

```
Uploading bundle for application: 83537...
Error: Unable to retrieve package records for the following packages:
- 'benchmarkmeData'
Called from: getPackageRecords(inferredPkgsNotInLib, project = project, available = available, 
    check.lockfile = TRUE, fallback.ok = fallback.ok)
```

Running it through the debugger, in the above function `lib.loc` is `NULL` and `fallbackPkgRecords` is `list()`

**Comment by kevinushey** [comment]
Hmm... What does `available` look like? Do you see your `benchmarkmeData` in the output of `available.packages()`?

**Comment by kevinushey** [comment]
Oh, do you by any chance have a locally built copy of `benchmarkmeData` installed? You might need to re-install it from your drat repository before uploading.

**Comment by csgillespie** [comment]
Answering both your comments:
```
R> "benchmarkmeData" %in% available.packages()
[1] TRUE
```

Delete local version

```
Uploading bundle for application: 83537...
Error: 
* Application depends on package "benchmarkmeData" but it is not installed.
  Please resolve before continuing.
In addition: Warning message:
Unable to package DESCRIPTION files: Couldn't find DESCRIPTION file for benchmarkmeData 
```

Reinstalling from `drat`

```
Uploading bundle for application: 83537...
Error: Unable to retrieve package records for the following packages:
- 'benchmarkmeData'
```

**Comment by kevinushey** [comment]
One more thing to try -- can you add `Repository: drat` to your package's `DESCRIPTION` file and re-upload?

If you run `readLines(system.file("DESCRIPTION", package = "benchmarkmeData"))`, do you see the `Repository:` field in the output?

**Comment by csgillespie** [comment]
I've tried various combinations of 

```
Repository: drat
Repository: http://csgillespie.github.io/drat/
Additional_repositories: http://csgillespie.github.io/drat/
```

of adding to the DESCRIPTION file no luck

Running `readLines` shows the `Repository` field. Is there another non-cran package you works, that I could try, i.e. is the problem non-cran packages in general or this particular package.

**Comment by kevinushey** [comment]
I'll try and play around here to see if I can figure out what's going on -- shinyapps + packrat should be able to understand CRAN-like repositories (e.g. drat), so something must be up with the packrat.

**Comment by csgillespie** [comment]
The package is now on CRAN and I can deploy the app as usual.

**Comment by kevinushey** [comment]
Based on the package version here: https://github.com/csgillespie/drat/blob/gh-pages/src/contrib/benchmarkmeData_0.2.2.tar.gz

The repository field is not populated, so packrat cannot and does not assume the package was retrieved from a CRAN-like repository.

If you populate the package's DESCRIPTION field with `Repository: drat` before upload, then it should work as expected.

**Comment by csgillespie** [comment]
So does `packrat` automatically convert

```
Repository: XXX
``` 
to

```
http://XXX.github.io/drat/
```
?

I did have the package locally installed. I also added the line

```
Additional_repositories: http://csgillespie.github.io/drat/
```

Which CRAN's win-builder used.

**Comment by kevinushey** [comment]
Right now, packrat does the following things when determining whether a package came from a CRAN-like repository. Packrat:

1. Calls `available.packages()` to get the set of available packages for all active CRAN-like repositories; that is, repositories enumerated in `getOption("repos")`. This should include `drat` repositories, assuming their `PACKAGES` and `PACKAGES.gz` files are up to date.

2. Checks for the `Repository:` field in the package's `DESCRIPTION` file for a repository name in the installed package; if one exists and matches an active repository name (ie, currently available in `getOption("repos")`), then it's assumed that the package was retrieved from a CRAN-like repository and can be installed with `install.packages()`. If no repository field is found, it is assumed that the package was installed from source (and can't, or shouldn't, be retrieved from CRAN).

The crux of the issue (I believe) is that packages uploaded to a `drat` repository should have their `DESCRIPTION` file modified to indicate a repository name.

**Comment by csgillespie** [comment]
OK, I think I now understand the issue (and solution). 

I think it would be worthwhile for packrat to also check for an `Additional_repositories:` field and add the corresponding entry as a possible repo.
